version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:latest@sha256:9d44331c7ab5c6d6138775f4441aa97dfd81b18c7bfecd8992054b2a6f7461b9
    restart: on-failure:0
    ports:
     - "8080:8080"
    environment:
      CONTEXTIONARY_URL: contextionary:9999
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "./weaviate-data"
      DEFAULT_VECTORIZER_MODULE: text2vec-contextionary
      ENABLE_MODULES: text2vec-contextionary,backup-filesystem
      BACKUP_FILESYSTEM_PATH: "/tmp/backups"
  contextionary:
    image: semitechnologies/contextionary:en0.16.0-v1.1.0
    ports:
      - "9999:9999"
    environment:
      OCCURRENCE_WEIGHT_LINEAR_FACTOR: 0.75
      EXTENSIONS_STORAGE_MODE: weaviate
      EXTENSIONS_STORAGE_ORIGIN: http://weaviate:8080
      NEIGHBOR_OCCURRENCE_IGNORE_PERCENTILE: 5
      ENABLE_COMPOUND_SPLITTING: 'false'
