---
version: '3.4'
services:
  weaviate-auth-wcs-noscopes:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8086'
      - --scheme
      - http
      - --write-timeout=600s
    image: semitechnologies/weaviate:1.18.0-alpha.0-be532d2
    ports:
      - 8086:8086
    restart: on-failure:0
    environment:
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      AUTHENTICATION_OIDC_ENABLED: 'true'
      AUTHENTICATION_OIDC_CLIENT_ID: 'wcs'
      AUTHENTICATION_OIDC_ISSUER: 'https://auth.wcs.api.semi.technology/auth/realms/SeMI'
      AUTHENTICATION_OIDC_USERNAME_CLAIM: 'email'
      AUTHENTICATION_OIDC_GROUPS_CLAIM: 'groups'
      AUTHORIZATION_ADMINLIST_ENABLED: 'true'
      AUTHORIZATION_ADMINLIST_USERS: 'ms_2d0e007e7136de11d5f29fce7a53dae219a51458@existiert.net'
...
