on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:


jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: "Install dependencies"
      run: |
        npm install
        ci/run_dependencies.sh
    - name: "Run tests with authentication tests"
      if: ${{ !github.event.pull_request.head.repo.fork }}
      env:
        OKTA_DUMMY_CI_PW: ${{ secrets.OKTA_DUMMY_CI_PW }}
        WCS_DUMMY_CI_PW: ${{ secrets.WCS_DUMMY_CI_PW }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        OKTA_CLIENT_SECRET: ${{ secrets.OKTA_CLIENT_SECRET }}
      run: |
        npm test
        npm run build
    - name: "Run tests without authentication tests (for forks)"
      if: ${{ github.event.pull_request.head.repo.fork }}
      run: |
        npm test
        npm run build
    - name: "Stop weavaite"
      run: ci/stop_dependencies.sh

  deploy:
    needs: Tests
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci && npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
